// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB22OJ4AP3c_VmMDEN1G89g0joTo-1INBY',
    appId: '1:1095175289735:android:e79e6322572cdf38683122',
    messagingSenderId: '1095175289735',
    projectId: 'pfe-app-e5e75',
    storageBucket: 'pfe-app-e5e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5l2G9j6xzt752ZS9Hn-pDLVQ9M0WY0Dk',
    appId: '1:1095175289735:ios:2cad6104c8c29145683122',
    messagingSenderId: '1095175289735',
    projectId: 'pfe-app-e5e75',
    storageBucket: 'pfe-app-e5e75.appspot.com',
    iosBundleId: 'com.example.orientationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3R1Ci-zYJIhO_K1CXBV2uJADu1y7k98A',
    appId: '1:1095175289735:web:73e3e7bdfe077dd6683122',
    messagingSenderId: '1095175289735',
    projectId: 'pfe-app-e5e75',
    authDomain: 'pfe-app-e5e75.firebaseapp.com',
    storageBucket: 'pfe-app-e5e75.appspot.com',
  );
}
